site_name: Blue Team Almanac
repo_url: https://github.com/blueteamalmanac/blueteamalmanac.github.io
repo_name: blueteamalmanac/blueteamalmanac.github.io
plugins:
  - search
  - glightbox
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
extra:
  generator: false

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
